######################################################################
# Automatically generated by qmake (3.0) pon. lis 7 13:09:22 2016
######################################################################
CONFIG += c++14
CONFIG += qt gui
QT += core
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += qt_qCompress.cpp
