######################################################################
# Automatically generated by qmake (3.0) ?r. pa? 12 23:10:21 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += cpuThreads.cpp
