######################################################################
# Automatically generated by qmake (3.0) ?r. mar 1 12:53:20 2017
######################################################################
CONFIG += C++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += minimal.cpp
