######################################################################
# Automatically generated by qmake (3.0) wt. lut 28 07:30:19 2017
######################################################################
CONFIG = c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += mapD.cpp
