######################################################################
# Automatically generated by qmake (3.0) ?r. mar 1 09:05:43 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += mapDpar.cpp
