######################################################################
# Automatically generated by qmake (3.0) pt. maj 5 11:45:01 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += listExample.cpp
