######################################################################
# Automatically generated by qmake (3.0) czw. mar 9 06:32:49 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += LUT.cpp
