######################################################################
# Automatically generated by qmake (3.0) pon. lis 21 12:19:54 2016
######################################################################
CONFIG += c++14
CONFIG += warn_off
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += reg.cpp
