######################################################################
# Automatically generated by qmake (3.0) pon. mar 13 12:49:10 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += staticVecD.cpp
