######################################################################
# Automatically generated by qmake (3.0) pon. sty 30 13:29:04 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += compress.hpp #zlib.h zconf.h
SOURCES += compress.cpp

LIBS += -lz