######################################################################
# Automatically generated by qmake (3.0) czw. mar 2 10:36:28 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += vecCopy.cpp
