######################################################################
# Automatically generated by qmake (3.0) pon. lis 7 11:16:27 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += saveToFile.cpp
