######################################################################
# Automatically generated by qmake (3.0) czw. kwi 27 16:54:07 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += fpFile.cpp
