######################################################################
# Automatically generated by qmake (3.0) pon. pa? 17 09:50:53 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += systemComm.cpp
