######################################################################
# Automatically generated by qmake (3.0) wt. pa? 11 15:02:37 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += Matrix.h headers.h
SOURCES += matrices.cpp
