######################################################################
# Automatically generated by qmake (3.0) pon. pa? 17 12:46:46 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += variables.cpp
