######################################################################
# Automatically generated by qmake (3.0) pt. cze 2 12:21:58 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += gotoEndFor.cpp
