######################################################################
# Automatically generated by qmake (3.0) pt. maj 5 13:40:46 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += stlContainers.cpp
