######################################################################
# Automatically generated by qmake (3.0) czw. mar 2 11:23:56 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += printf.cpp
