######################################################################
# Automatically generated by qmake (3.0) wt. mar 7 07:29:05 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += multiMapVector.cpp
