######################################################################
# Automatically generated by qmake (2.01a) niedz. cze 19 16:54:43 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += GMM_ex1.cpp
LIBS += -litpp
