######################################################################
# Automatically generated by qmake (3.0) czw. mar 9 11:11:51 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += addDisassembly.cpp
