######################################################################
# Automatically generated by qmake (3.0) pt. maj 5 13:40:46 2017
######################################################################
CONFIG += c++11
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3
QMAKE_LFLAGS_RELEASE -= -O1
QMAKE_LFLAGS_RELEASE += -O3
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += stlContainers.cpp
