######################################################################
# Automatically generated by qmake (3.0) pt. lis 4 10:14:13 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += modulo.cpp
