######################################################################
# Automatically generated by qmake (3.0) pon. cze 5 09:23:55 2017
######################################################################
CONFIG += C++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += datatypesToChar.cpp
