######################################################################
# Automatically generated by qmake (3.0) wt. cze 6 20:05:44 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += mmappedRead.cpp
