######################################################################
# Automatically generated by qmake (3.0) pt. lut 10 10:51:03 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += newDel.cpp
