######################################################################
# Automatically generated by qmake (3.0) czw. pa? 13 10:37:00 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += opto.cpp
