######################################################################
# Automatically generated by qmake (3.0) ?r. mar 1 11:52:33 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += sources.cpp vector1D1D.cpp
