######################################################################
# Automatically generated by qmake (3.0) pt. mar 10 09:18:53 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += vecTmp.cpp
