// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef hello_h
#define hello_h
#include <FL/Fl.H>
void hello_button_CB(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *Hello;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *disp;
#endif
