// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "hello.h"

void hello_button_CB(Fl_Widget*, void* userdata) {
  printf("Hello Button CallBack : \"%s\'\n", (char*)userdata);

  Fl_Text_Buffer *buff = new Fl_Text_Buffer();
  disp->buffer(buff);
  buff->text("Hi!\n\nThere!\n");
}

Fl_Button *Hello=(Fl_Button *)0;

Fl_Text_Display *disp=(Fl_Text_Display *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(800, 400, "Hello");
    w = o; if (w) {/* empty */}
    o->tooltip("Hello main window");
    o->labelfont(4);
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Hello = new Fl_Button(334, 15, 131, 30, "Hello Button");
      Hello->callback((Fl_Callback*)hello_button_CB, (void*)("001"));
      Hello->window()->hotspot(Hello);
    } // Fl_Button* Hello
    { disp = new Fl_Text_Display(45, 60, 695, 275);
    } // Fl_Text_Display* disp
    o->end();
    o->resizable(o);
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
