######################################################################
# Automatically generated by qmake (3.0) pt. pa? 14 09:27:29 2016
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
HEADERS += headers.h
SOURCES += asynchro.cpp
