######################################################################
# Automatically generated by qmake (3.0) pt. lut 3 13:30:35 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += autoVec.cpp
